---
title: "`r params$name`'s PHUSE Connect Presenter History"
output: html_document
params:
  name: "Veramed"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(httr)
library(jsonlite)

library(ggplot2)
library(sf)

library("rnaturalearth")
library("rnaturalearthdata")


# from https://gist.github.com/rentrop/83cb1d8fc8593726a808032e55314019
url <- "https://phuse.global/api/graphql"
GQL <- function(query, 
                ..., 
                .token = NULL,
                .variables = NULL, 
                .operationName = NULL, 
                .url = url){
  pbody <- list(query = query, variables = .variables, operationName = .operationName)
  if(is.null(.token)){
    res <- POST(.url, body = pbody, encode="json", ...)
  } else {
    auth_header <- paste("bearer", .token)
    res <- POST(.url, body = pbody, encode="json", add_headers(Authorization=auth_header), ...)
  }
  res <- content(res, as = "parsed", encoding = "UTF-8")
  if(!is.null(res$errors)){
    warning(toJSON(res$errors))
  }
  res$data
}

as_company <- GQL(glue::glue('query{
  archives(sort: "year:DESC", start: 0, where: { event: "Connect" company_contains: "<params$name>" }) {
    event
    year
    city
    region
    title
    author
    company
    co_author
    educational_category
    keywords
    filename
  }
}', .open="<", .close=">"))$archives

all_connects <- do.call(bind_rows, as_company)
```

## Your first connect...

```{r first_data, include=FALSE}
first <- arrange(all_connects, year, desc(region))[1,]
was_virtual <- if_else(first$city == "Virtual", T, F)
```

The first connect someone from this company presented was PHUSE `r first$region` `r first$year`!

```{r first_city, eval=!was_virtual, include=!was_virtual}
city_req <- GET(glue::glue("https://api.api-ninjas.com/v1/city?name={first$city}"), 
                add_headers("X-Api-Key" = Sys.getenv("API_NINJAS_KEY")))
  # If we got a good response
  if (city_req$status_code == 200 && !identical(content(city_req),list())) {
    city <- content(city_req)[[1]]
    
    # get the country it was held in
    country_req <- GET(glue::glue("https://api.api-ninjas.com/v1/country?name={city$country}"), 
                add_headers("X-Api-Key" = Sys.getenv("API_NINJAS_KEY")))
    # If we got a good response
    if (country_req$status_code == 200 && !identical(content(country_req), list())) {
      country <- content(country_req)[[1]]
    } else {
      # don't print the city info
      was_virtual <- T
    }
  } else {
    # don't print the city info
    was_virtual <- T
  }
```


`r if (was_virtual) {"Your first PHUSE was virtual!"} else {glue::glue("This PHUSE was held in {first$city}, {country$name}. This city has a population of {format(city$population, big.mark=',')}.")}`


## Your connect map

```{r get_loc}
raw <- lapply(unique(all_connects$city),\(x) GET(glue::glue("https://api.api-ninjas.com/v1/city?name={x}"), 
            add_headers("X-Api-Key" = Sys.getenv("API_NINJAS_KEY"))) |> content())

location <- do.call(bind_rows, raw)
```

```{r make_plot, eval=!identical(location, tibble())}
world <- ne_countries(scale = "medium", returnclass = "sf")

ggplot(world) + 
  geom_sf() +
  geom_point(data = location, aes(x = longitude, y = latitude), size = 4, shape = 23, fill = "blue") +
  coord_sf(xlim=c(min(location$longitude) - 8, max(location$longitude + 8)), 
           ylim=c(min(location$latitude) - 8, max(location$latitude + 8)),
           expand = FALSE) +
  theme_minimal()
```